using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class IntSyncModel
{
    [RealtimeProperty(1, true, true)]
    private int _num;
}
/* ----- Begin Normal Autogenerated Code ----- */
public partial class IntSyncModel : IModel {
    // Properties
    public int num {
        get { return _cache.LookForValueInCache(_num, entry => entry.numSet, entry => entry.num); }
        set { if (value == num) return; _cache.UpdateLocalCache(entry => { entry.numSet = true; entry.num = value; return entry; }); FireNumDidChange(value); }
    }
    
    // Events
    public delegate void NumDidChange(IntSyncModel model, int value);
    public event         NumDidChange numDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool numSet;
        public int  num;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public IntSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireNumDidChange(int value) {
        try {
            if (numDidChange != null)
                numDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Num = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _num = num;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Num, (uint)_num);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.numSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.Num, (uint)entry.num);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.Num, (uint)_num);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.numSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.numSet)
                    stream.WriteVarint32((uint)PropertyID.Num, (uint)entry.num);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool numExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.numSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Num: {
                    int previousValue = _num;
                    
                    _num = (int)stream.ReadVarint32();
                    
                    if (!numExistsInChangeCache && _num != previousValue)
                        FireNumDidChange(_num);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
